services:
  suma:
    build: ./suma
    ports:
      - "8001:8000"
    networks:
      - shape-net

  resta:
    build: ./resta
    ports:
      - "8002:8000"
    networks:
      - shape-net

  ecuacion:
    build: ./ecuacion
    ports:
      - "8003:8000"
    networks:
      - shape-net
    depends_on:
      - suma
      - resta

  almacenar:
    build: ./almacenar
    ports:
      - "8004:8000"
    networks:
      - shape-net
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: "mysql"
      MYSQL_USER: "myuser"
      MYSQL_PASSWORD: "mypassword123"
      MYSQL_DATABASE: "resultados_db"

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_HOST: "mysql"
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword123
      MYSQL_DATABASE: resultados_db
    ports:
      - "3307:3306"
    networks:
      - shape-net
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

networks:
  shape-net:
    driver: bridge

volumes:
  mysql_data:
